# Generated by Django 3.2.4 on 2021-07-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_auto_20210716_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='what_post',
            new_name='title',
        ),
    ]
